trigger:
- backend

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- task: CopyFiles@2
  displayName: 'Copy Azure Function files to artifacts'
  inputs:
    SourceFolder: azure_function_backend
    TargetFolder: '$(build.artifactstagingdirectory)/azure_function_backend'

- bash: |
   python3 -m venv worker_venv
   source worker_venv/bin/activate
   pip3 install setuptools
   pip3 install -r requirements.txt
  workingDirectory: '$(build.artifactstagingdirectory)/azure_function_backend'
  displayName: 'Install Application Dependencies'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/'